server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   # don't register itself
    fetchRegistry: false         # don't fetch its own registry
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0  # faster startup

management:
  endpoints:
    web:
      exposure:
        include: health,info