server:
  port: 8084

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:55433/user_db
    username: user_svc
    password: user_secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-at-least-32chars!!}  # must match auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
